### ISSUE TITLE
it can not perform banding event when use utap to bind a button element

### ISSUE THREAD

**Issue by sunliying** [mmikowski/jquery.event.ue#10]
hi, I found somthing wrong with the utap event when I tried to bind an event to a button element, it can not trigger the callback,just like
$('.ok').bind('utap.utap',onTapLogin);
onTapLogin function won't be triggered; and if $(".ok") is a submit button , my login-page will exit automaticly.
i am confused and i don't know if i did something wrong 
and last forgive my poor English

**Comment by mmikowski** [comment]
The issue is probably with the submit button, which has a default action.  You either need to preventDefault(), or, better yet, don't use a submit button.  Instead, have the JS submit the form when a button is tapped.  Try this:

```
<div id="ok">Submit</id>

<script>
$(function (){
  $('#ok').on( 'utap', onTapLogin );
});
</script>

```

You can bind an 'onKeydown' event to detect if the user is pressing the Enter key and process the form then too.

Please let me know if that works :)

**Comment by sunliying** [comment]
it performs well if I change the button elment to a div element       
it is not bacause preventDefault() or return false,because it even won't perform the callback function. but it will perform well if I use `click` when binding a button element.

**Comment by mmikowski** [comment]
Check out the ignore_select attribute in the settings on the latest release.  It lists the selectors that are ignored if the action begins on them.  Currently these include textareas, input areas, and selects.  You can modify this as needed.  It is almost certainly the issue you were seeing before, as the old selector was :input which picked all form elements.  Please reopen if this remains a concern.
