### ISSUE TITLE
site becomes unscrollable and unzoomable on a mobile device if I use a utap event

### ISSUE THREAD

**Issue by saraf** [mmikowski/jquery.event.ue#12]
Greetings Mike,

Thanks for the awesome book and the good work.

I need to use the utap event for a div on a spa that I am building. I have the following code:

```
         var entryDiv = $("#entry"+statusUpdateMap.entryId);         
         entryDiv.unbind('utap.utap').bind('utap.utap', function () {
             spa.model.bdv.askForLogDetails(statusUpdateMap.entryId);
         });

```
If I remove this bit of code, the site is zoomable and scrollable. How do I specify that I want the page to be zoomable and scrollable on a mobile device when using this library?

**Comment by mmikowski** [comment]
The library captures all touch events and then delegates to handlers. This means that punch to zoom and other touch events are captured and blocked from bubbling by default. I am dealing with a similar issue currently and will keep you appraised on my progress. 

In the near term, you may either handle the zoom events or use click instead of utap.  One of the key objectives for this plugin was to block the default zoom behavior, as we wanted the user to zoom in on a workspace without changing the size of all the elements surrounding it. The same goes for inertia scrolling (see the dragscroll plugin to provide similar capability though).

**Comment by saraf** [comment]
Okay! I ended up using click instead of utap for the moment.

**Comment by mmikowski** [comment]
Saraf, the solution was there all along :)

Check out the option called "ignore_select".  There you place selectors of elements you don't want to have considered by dragscroll.  You could apply this to any specific class.  In version 1.3.2, I reset the default go ignore textareas, text inputs, and selects.  I do not ignore buttons, however, as I want to use utap with those.  You may adjust as you like.

Please reopen this if this does not resolve your issue!
