### ISSUE TITLE
failing in iOS simulator

### ISSUE THREAD

**Issue by suzerain** [mmikowski/jquery.event.ue#8]
Was using this on an app, but the library is returning this error when in the iOS simulator (iOS 8.1): "TypeError: undefined is not an object (evaluating 'o_event.changedTouches')". The error is on Line 656, after a reference to "event.originalEvent" (this property obviously doesn't exist).

I'd help fix this but not sure yet what that code is trying to do.

**Comment by mmikowski** [comment]
Original event apparently is not defined in the iOS8.1 simulator.  Since I don't own a Mac, I can't run this to check.  However, the fix to avoid a fatal exception is easy:

First, 'a_touches' should be renamed to 'touch_list'.  Next, we should check if
 the original event is undefined; if so, set the touch list to an empty array.  If it is defined, set the touch list equal to the changedTouches property, or to an empty array if that is not defined.

After the rename, this should be all that is needed at line 656:

    touch_list = o_event ? o_event.changedTouches || [] : []

I will roll this into an upcoming release.  But the fix above should solve your problem.

**Comment by suzerain** [comment]
That did indeed get rid of the fatal error. 

However, in the iOS simulator there are other issues making it not work (more complex to explain, but it revolves around the preventDefault() calls with touchstart and touchmove around line 666). When those lines are included, it seems all touch events are intercepted but not passed through (or something...it interferes with scrolling the screen contents, for example). I have not yet resolved this.

**Comment by mmikowski** [comment]
Thank you for the feedback, suzerain.  I have fixed the fatal error in a release today.  And yes, the preventDefault() calls does prevent the default downstream behavior.  This can be challenging for scroll areas.  The trick is to disable the events when working with a scroll-able areas or use a custom scroll area (which I have done).  I propose we close this issue after your confirmation of the fix, and create new issue for the preventDefault() condition that you are seeing.  We can probably devise a solution, possibly without even changing this plugin.

**Comment by suzerain** [comment]
That makes sense, seeing as it's two separate issues.  If I can help with the other bit, let me know.

**Comment by mmikowski** [comment]
Thank you Suzerain!  I look forward to details on the new issue.
